# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version=2.2+1.21.1
maven_group=me.luligabi.enhancedworkbenches
archives_name=enhanced_workbenches
enabled_platforms=fabric,neoforge
active_item_viewer=emi
# Minecraft properties
minecraft_version=1.21.1
# Common
architectury_api_version=13.0.8
yacl_version=3.6.2+1.21
kuma_api_version=1.1.0-SNAPSHOT
balm_version=21.0.22-SNAPSHOT
crafting_tweaks_version=21.1.5+1.21.1
rei_version=16.0.788
emi_version=1.1.22+1.21.1
jei_version=19.21.0.247
# Fabric
fabric_loader_version=0.16.10
fabric_api_version=0.114.0+1.21.1
modmenu_version=11.0.3
# Neoforge
neoforge_version=21.1.93