modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL="https://github.com/Luligabi1/EnhancedWorkbenches/issues"
license = "Apache 2.0"

[[mods]]
modId = "enhancedworkbenches"
version = "${version}"
displayName = "Enhanced Workbenches"
authors = "Luligabi1"
credits="""
Assets by gonsawa_

Translations and improvements by DenisMasterHerobrine, VeiTr, unroman, unilock, Abbie5, neofuchsy, ProdOrDev
"""
description ="""
Better crafting solutions through the ages brought onto Modern Minecraft.
"""
logoFile = "icon.png"

[[dependencies.enhancedworkbenches]]
modId = "architectury"
type = "required"
versionRange = "[13,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.enhancedworkbenches]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.enhancedworkbenches]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"
[[mixins]]
config = "enhancedworkbenches.mixins.json"